version: '3'

services:
  k2sandbox:
    build:
      context: .
      dockerfile: docker/Dockerfile.base
      args:
        - TEMPLATE_DIR=templates
    image: k2data/sandbox-base:latest
    ports:
      - "8888:8888"
      - "3000:3000"
      - "49999:49999"
    volumes:
      - ./templates:/templates
      - ./workspace:/home/user/workspace 