version: '3'

services:
  sandbox-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - sandbox-network

networks:
  sandbox-network:
    driver: bridge 